spring:
  # H2 \uC124\uC815 \uC815\uBCF4
  h2:
    console:
      enabled: true
      path: /h2-console
  # H2 \uC5F0\uACB0 \uC815\uBCF4
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

