server:
  port: 80

spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/event-service
    username: sa
    password:

  sql:
    init:
      mode: ALWAYS

logging:
  level:
    org:
      springframework.web: debug
